name: demo_app
description: Fatigue Tree demo
publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  fl_chart: ^0.66.2
  flutter_blue_plus: ^1.32.6
  permission_handler: ^11.3.1
  flutter_bluetooth_serial: ^0.4.0
  provider: ^6.1.2
  lottie: ^3.1.2
  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/beep.wav

flutter_launcher_icons:
  android: true
  ios: false
  image_path_android: assets/icon/app_icon_fore.png
  adaptive_icon_background: "#1D3B33"
  adaptive_icon_foreground: assets/icon/app_icon_fore.png
  min_sdk_android: 21
