name: demo_app
description: Fatigue Tree demo
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # --- 以下是程式實際用到的套件 ---
  dio: ^5.7.0
  fl_chart: ^0.66.2
  flutter_blue_plus: ^1.32.6
  permission_handler: ^11.3.1

  # 如果你還想支援舊版 Serial (非 BLE)，才需要這行
  flutter_bluetooth_serial: ^0.4.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
